"""followers

Revision ID: 18505a7f8a7e
Revises: f54b5ad58d8b
Create Date: 2022-09-01 04:44:21.074554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18505a7f8a7e'
down_revision = 'f54b5ad58d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
